### ISSUE TITLE
In python actions, all the parameters defined by the end of the script must be serializable.

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/docs#17]
From troubleshooting email thread with a contributor.

**Comment by levice14** [comment]
I also experienced this issue.. one method is to remove non-serializable variables before returning from the script (e.g. `del non_serializable_var`)

**Comment by levice14** [comment]
What I think we should do here is: printing an appropriate error message to specify which variable is not serializable and a suggestion on how to solve it (e.g. `del my_var`). 

Suppressing all the variables that are not serilizable is not a good solution since user should be aware of what his script does and he will not wonder why his outputs are filled with null values.

WDYT? @meirwah @oritstone @orius123 @gituser173 @mihaitusa

.. and we should open an issue and solve it in cloud-slang repo first - CLI currently prints:

```
Command failed java.lang.RuntimeException: Slang Error : null
```

**Comment by meirwah** [comment]
Agree with this approach @Bonczidai

**Comment by oritstone** [comment]
:+1:

**Comment by orius123** [comment]
:+1:
