### ISSUE TITLE
Update Repo List 

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/docs#60]
Add Atom repo and any new content folders

**Comment by SamMarkowitz** [comment]
I wonder if the list at http://cloudslang-docs.readthedocs.org/en/v0.8/developer_contribution/ is more trouble than it is worth. Maybe just a link to the content repo docs page (which needs to be improved)? @oritstone @meshipeer

**Comment by oritstone** [comment]
I think that in general we would like to improve the messaging of our documentation, so that the value we give - meaning story use cases (content) will be more apparent.
I guess we will probably pick a different approach than the current list of content which needs to be constantly updated, but let's leave it as is until we get to a decision of how we actually do it.
